### ISSUE TITLE
Argument order of input/parameter

### ISSUE THREAD

**Issue by odashi** [odashi/primitiv#57]
Related to: #54.

Currently, `operators::input` and initialization functions of `Parameter` take always two arguments: `shape` and `data/initializer`, and they are commonly passed with the following order: `foo(shape, data/initializer)`.

On the other hand, in the Python implementation, the data could be an `ndarray` objects which have their own shapes. The Python interface is implemented that implicitly extracts the shape from the given data, and users are no longer necessary to pass explicit `shape` argument to above functions. I.e., the `data` is almost the first argument: `foo(data)` in this case, and this usage looks superficially different against C++ interfaces.

To avoid this divergence, the argument order of C++ implementations probably should be fixed as `foo(data/initializer, shape)`.

However, the C++ implementation does not have the data structure similar to `ndarrays`, and basically the `shape` argument could be an *always necessary* argument. In addition, this change may disable passing *default initializers*, an commonly-used feature in other deep learning toolkits.
And in fact, the first argument of `ndarray` is basically `shape`. ([documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.html))

Eventually, my current thought is that:
* `shape` should be always the first argument in all languages.
* If `data` have own shape (this is not a common, i.e., language/toolkit-dependent case), `shape` could be excluded from the arguments.

**Comment by vbkaisetsu** [comment]
Additional info:

Currently, Python frontend uses keyword arguments for `shape` and `initializer` to solve this problem.
It requires specifiers such as `initializer=`.

```python
# w/ shape & w/ initializer
param = Parameter(shape, init_var)
# w/o shape & w/ initializer (w/ keyword specifiers)
param = Parameter(initializer=init_var)
# w/ shape & w/o initializer
param = Parameter(shape) # DOES NOT WORK
# w/o shape & w/ initializer (w/o keyword specifiers)
param = Parameter(init_var) # Currently does not work (needs complicated implementation)
```

**Comment by odashi** [comment]
I guess that the `Parameter` class would not be initialized with specific `ndarray`, i.e., most users use only the first case.

**Comment by odashi** [comment]
But the similar issue is still alive about `operators.input`.

**Comment by odashi** [comment]
One workaround is that using `*args` and `*kwargs` instead of explicit arguments, and analyzes the arguments ourselves. In this case we should add enough docstrings for each function.
