### ISSUE TITLE
OpenCL Support

### ISSUE THREAD

**Issue by vbkaisetsu** [odashi/primitiv#80]
This issue tracks the current status of OpenCL implementation.

* Branch: https://github.com/odashi/primitiv/tree/feature/opencl
* Target OpenCL version: 1.2?
* Dependency: [OpenCL C++ header (CLHPP)](https://github.com/KhronosGroup/OpenCL-CLHPP), [clBLAS](https://github.com/clMathLibraries/clBLAS)

**NOTE:** CLHPP is distributed from Khronos Group that decides OpenCL specification. However, at least in Mac OS X, C header is contained but CLHPP is not contained in the default.

Debian/Ubuntu packages for building: opencl-headers, ocl-icd-opencl-dev, libclblas-dev

TODO:
* Memory pool -- *done*
* Random functions -- *done*
* Pimpl -- *done*
* Test cases -- *done*
* Documentation (Build and Usage)
* Optimizing implementations

**Comment by odashi** [comment]
There are 2 different headers in OpenCL binding: `cl.hpp` and `cl2.hpp`. `cl2.hpp` is newer but also included in Debian/Ubuntu repository. Why does current implementation use the older header?

**Comment by odashi** [comment]
In Mac, OpenCL core libraries are installed by default, but the location is different: `OpenCL/blah`.
C++ headers should be installed from source, but they would be installed in `CL/blah` by using usual way:
```shell
$ git clone https://github.com/KhronosGroup/OpenCL-CLHPP -b v2.0.10
$ cd OpenCL-CLHPP
$ mkdir build
$ cd build
$ cmake .. -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF
$ make
$ make install
```

And clBLAS should be installed from source too:
```shell
$ git clone https://github.com/clMathLibraries/clBLAS -b v2.12
$ cd clBLAS
$ mkdir build
$ cd build
$ cmake ../src -DBUILD_TEST=OFF
$ make
$ make install
```

After installing clBLAS, `clBLASConfig.cmake` is also installed in the local directory and we probably can use `find_package(clBLAS)` command in our CMake script.

**Comment by odashi** [comment]
[Mac] OpenCL libraries are installed in `/System` directory (which even the root user can't modify) and `find_package(OpenCL)` command finds this. As a result, the include path does not cover the directory that contains CLHPP headers. Probably we need an original CMake script that finds CLHPP headers.

**Comment by vbkaisetsu** [comment]
OpenCL C++ header version is changed to 2.0 at https://github.com/odashi/primitiv/commit/8ba83e16a76f99d94ed6e0c4453e18bb384445a5

**Comment by vbkaisetsu** [comment]
We can make data transportation faster using `CL_MEM_USE_HOST_PTR` and `CL_MEM_ALLOC_HOST_PTR` options of `cl::Buffer` and `clEnqueueMapBuffer()` function.

When `CL_MEM_USE_HOST_PTR` is specified, OpenCL creates a zero copy buffer that refers a memory on the host allocated by a user. `clEnqueueMapBuffer()` returns a pointer of the memory that is allocated using `CL_MEM_USE_HOST_PTR` or `CL_MEM_ALLOC_HOST_PTR`. Using these options, we can return a vector result without copying data.

Both Intel's and AMD's GPU require 4 KiB (4096 bytes) aligned memory for `CL_MEM_USE_HOST_PTR` option,
and Intel says a total size of the memory must be a multiple of 64 bytes.
Therefore, we can not use this option for input data.

For more details, see:
https://software.intel.com/en-us/articles/getting-the-most-from-opencl-12-how-to-increase-performance-by-minimizing-buffer-copies-on-intel-processor-graphics
http://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/

**Comment by odashi** [comment]
Some errors occur when performing this branch on Intel GPUs due to:
- Insufficient precision of floating point calculations (maybe this is because of the driver implementation)
- Few thread configurations, e.g., only `[1024, 1, 1]` is available as the number of threads (inner GPU of Core i5).

The second issue makes performing `matmul` and `transpose` harder than other GPUs provided from NVidia/AMD. I guess it is better to omit this kind of GPUs from primitiv's support by commenting it in `opencl_device.h` and other main documents.

**Comment by odashi** [comment]
**Ubuntu, CUDA**
CUDA runtime provides `cl.hpp`, but does not provide `cl2.hpp`. We have to install it by ourselves.
BTW, we also have to install CLHPP and clBLAS by hand because apt libraries may conflict with CUDA.

**Comment by odashi** [comment]
**[OpenCL]**
According to some experiments, the destructor of cl::Buffer does **NOT** block the process until finishing kernel functions for some reason (why?). We have to manually wait for this by adding a barrier in the deleter:

```c++
// current deleter
return std::shared_ptr<void>(data, [](void *ptr) {
	delete static_cast<cl::Buffer *>(ptr);
});

// new deleter
return std::shared_ptr<void>(data, [&](void *ptr) {
	cmd_queue_.finish();  // always waits for terminating kernels.
	delete static_cast<cl::Buffer *>(ptr);
});
```
